version: '3.8'
services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=eksamen
    ports:
      - '5432:5432'

  hbase:
    container_name: hbase
    image: dajobe/hbase
    restart: always
    environment:
      - HBASE_USER=dev
      - HBASE=dev123
    ports:
    - '16010:16010'
    - '9095:9095'
    - '8085:8085'
    - '9090:9090'
    - '2181:2181'
    - '8080:8080'

  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment:
      - REDIS_USER=dev
      - PASSWORD=dev123
    ports:
      - '6379:6379'
 
  python3:
    build: .
    container_name: python3
    environment:
      # POSTGRES
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=eksamen
      # MONGO
      - MONGO_HOST=mongo
      - MONGO_USER=dev
      - MONGO_PASSWORD=dev
      - MONGO_PORT=27017
      # HBASE
      - HBASE_HOST=hbase
      - HBASE_PORT=9090
      # REDIS
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      - postgres
      - hbase
      - mongo
      - redis
    ports:
      - 5000:5000
