version: '3.8'
services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=eksamen
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  hbase:
    container_name: hbase
    image: dajobe/hbase
    restart: always
    environment:
      - HBASE_USER=dev
      - HBASE=dev123
    ports:
    - '16010:16010'
    - '9095:9095'
    - '8085:8085'
    - '9090:9090'
    - '2181:2181'
    - '8080:8080'
    volumes:
      - hbase:/var/lib/hbase/data

  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo/data

  redis:
    container_name: xredis
    image: redis:latest
    restart: always
    environment:
      - REDIS_USER=dev
      - PASSWORD=dev123
    ports:
      - '6379:6379'
    volumes: 
      - redis:/var/lib/redis/data
     
  python3:
    build: .
    container_name: python3
    command: python3 main.py
    environment:
      # POSTGRES
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_DB=eksamen
      # MONGO
      - MONGO_HOST=mongo
      - MONGO_USER=dev
      - MONGO_PASSWORD=dev
      - MONGO_PORT=27017
      # HBASE
      - HBASE_HOST=hbase
      - HBASE_PORT=16010
      - HBASE_USER=dev
      - HBASE_DB=dev123
    depends_on:
      - postgres
      - hbase
      - mongo
    volumes:
      - python3:/var/lib/python3/data
    ports:
      - 5000:5000



volumes:
  postgres:
    driver: local
  hbase:
    driver: local
  mongo:
    driver: local
  redis:
    driver: local
  python3:
    driver: local